V1 release
stakater/k8s-cost-optimizer pull request #1
Opened 2022-03-18 11:17 UTC by talha0324

Feature list:
- Patch resources with the provided config
- Check if pods can be evicted and rescheduled onto other nodes

2022-03-21 11:35 UTC, stakater-user commented
@talha0324 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/k8s-cost-optimizer/commit/2c9b939038454c22298ff871094457aaabd490b1/checks) has Failed!

2022-03-21 11:41 UTC, stakater-user commented
@talha0324 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/k8s-cost-optimizer/commit/7c96925af214da6fd315a56151df38b6a7bfc0a7/checks) has Failed!

2022-03-21 12:13 UTC, stakater-user commented
@talha0324 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/k8s-cost-optimizer/commit/fd81a4185ce2f9773d8dbc53c5a83dbb9d4a39ee/checks) has Failed!

2022-03-21 12:45 UTC, stakater-user commented
@talha0324 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/k8s-cost-optimizer/commit/1520a185d2172957e1cf0b00ffdb43f61eb0c6b8/checks) has Failed!

2022-03-21 13:28 UTC, stakater-user commented
@talha0324 Image is available for testing. `docker pull stakater/k8s-cost-optimizer:SNAPSHOT-PR-1-82a7ba5f`

2022-03-22 08:56 UTC, tanalam2411 requested changes

2022-03-22 08:56 UTC, tanalam2411 commented on Dockerfile
> +FROM scratch
Should we use `scratch` as the base image?

2022-03-22 09:02 UTC, stakater-user commented
@talha0324 Image is available for testing. `docker pull stakater/k8s-cost-optimizer:SNAPSHOT-PR-1-9e4ed385`

2022-03-22 09:09 UTC, tanalam2411 commented on Dockerfile
> +FROM scratch
I think scratch is good for now

2022-03-22 09:09 UTC, tanalam2411 approved these changes

2022-03-22 09:48 UTC, merged